// Code generated by "stringer -type Browser -trimprefix=B browser.go"; DO NOT EDIT.

package browser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bfirefox-0]
	_ = x[Bchromium-1]
}

const _Browser_name = "firefoxchromium"

var _Browser_index = [...]uint8{0, 7, 15}

func (i Browser) String() string {
	if i < 0 || i >= Browser(len(_Browser_index)-1) {
		return "Browser(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Browser_name[_Browser_index[i]:_Browser_index[i+1]]
}
