// Code generated by MockGen. DO NOT EDIT.
// Source: updater.go
//
// Generated by this command:
//
//	mockgen -source=updater.go -destination=updater_mock_test.go -package=updater
//

// Package updater is a generated GoMock package.
package updater

import (
	context "context"
	reflect "reflect"

	github "github.com/rusq/slackdump/v4/cmd/slackdump/internal/diag/updater/github"
	gomock "go.uber.org/mock/gomock"
)

// Mockfetcher is a mock of fetcher interface.
type Mockfetcher struct {
	ctrl     *gomock.Controller
	recorder *MockfetcherMockRecorder
	isgomock struct{}
}

// MockfetcherMockRecorder is the mock recorder for Mockfetcher.
type MockfetcherMockRecorder struct {
	mock *Mockfetcher
}

// NewMockfetcher creates a new mock instance.
func NewMockfetcher(ctrl *gomock.Controller) *Mockfetcher {
	mock := &Mockfetcher{ctrl: ctrl}
	mock.recorder = &MockfetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfetcher) EXPECT() *MockfetcherMockRecorder {
	return m.recorder
}

// ByTag mocks base method.
func (m *Mockfetcher) ByTag(ctx context.Context, tag string) (*github.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTag", ctx, tag)
	ret0, _ := ret[0].(*github.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTag indicates an expected call of ByTag.
func (mr *MockfetcherMockRecorder) ByTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTag", reflect.TypeOf((*Mockfetcher)(nil).ByTag), ctx, tag)
}

// Latest mocks base method.
func (m *Mockfetcher) Latest(ctx context.Context) (*github.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(*github.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockfetcherMockRecorder) Latest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*Mockfetcher)(nil).Latest), ctx)
}
