// Code generated by "stringer -type=ExportType -linecomment"; DO NOT EDIT.

package export

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TNoDownload-0]
	_ = x[TStandard-1]
	_ = x[TMattermost-2]
}

const _ExportType_name = "NoDownloadStandardMattermost"

var _ExportType_index = [...]uint8{0, 10, 18, 28}

func (i ExportType) String() string {
	if i >= ExportType(len(_ExportType_index)-1) {
		return "ExportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportType_name[_ExportType_index[i]:_ExportType_index[i+1]]
}
