package export

import (
	"fmt"
	"strings"
)

//go:generate go install golang.org/x/tools/cmd/stringer@latest

//go:generate stringer -type=ExportType -linecomment
type ExportType uint8

const (
	TNoDownload ExportType = iota // NoDownload
	TStandard                     // Standard
	TMattermost                   // Mattermost
)

// Set translates the string value into the ExportType, satisfies flag.Value
// interface.  It is based on the declarations generated by stringer.
func (e *ExportType) Set(v string) error {
	v = strings.ToLower(v)
	for i := 0; i < len(_ExportType_index)-1; i++ {
		if strings.ToLower(_ExportType_name[_ExportType_index[i]:_ExportType_index[i+1]]) == v {
			*e = ExportType(i)
			return nil
		}
	}
	return fmt.Errorf("unknown format: %s", v)
}
