// Copyright (c) 2021-2026 Rustam Gilyazov and Contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// Code generated by "stringer -type=ChunkType -trimprefix=C"; DO NOT EDIT.

package chunk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMessages-0]
	_ = x[CThreadMessages-1]
	_ = x[CFiles-2]
	_ = x[CUsers-3]
	_ = x[CChannels-4]
	_ = x[CChannelInfo-5]
	_ = x[CWorkspaceInfo-6]
	_ = x[CChannelUsers-7]
	_ = x[CStarredItems-8]
	_ = x[CBookmarks-9]
	_ = x[CSearchMessages-10]
	_ = x[CSearchFiles-11]
}

const _ChunkType_name = "MessagesThreadMessagesFilesUsersChannelsChannelInfoWorkspaceInfoChannelUsersStarredItemsBookmarksSearchMessagesSearchFiles"

var _ChunkType_index = [...]uint8{0, 8, 22, 27, 32, 40, 51, 64, 76, 88, 97, 111, 122}

func (i ChunkType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChunkType_index)-1 {
		return "ChunkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChunkType_name[_ChunkType_index[idx]:_ChunkType_index[idx+1]]
}
