// Code generated by "stringer -type=ChunkType -trimprefix=C"; DO NOT EDIT.

package chunk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMessages-0]
	_ = x[CThreadMessages-1]
	_ = x[CFiles-2]
	_ = x[CUsers-3]
	_ = x[CChannels-4]
	_ = x[CChannelInfo-5]
	_ = x[CWorkspaceInfo-6]
	_ = x[CChannelUsers-7]
	_ = x[CStarredItems-8]
	_ = x[CBookmarks-9]
	_ = x[CSearchMessages-10]
	_ = x[CSearchFiles-11]
	_ = x[CAny-255]
}

const (
	_ChunkType_name_0 = "MessagesThreadMessagesFilesUsersChannelsChannelInfoWorkspaceInfoChannelUsersStarredItemsBookmarksSearchMessagesSearchFiles"
	_ChunkType_name_1 = "Any"
)

var (
	_ChunkType_index_0 = [...]uint8{0, 8, 22, 27, 32, 40, 51, 64, 76, 88, 97, 111, 122}
)

func (i ChunkType) String() string {
	switch {
	case i <= 11:
		return _ChunkType_name_0[_ChunkType_index_0[i]:_ChunkType_index_0[i+1]]
	case i == 255:
		return _ChunkType_name_1
	default:
		return "ChunkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
