// Code generated by "stringer -type=fallbackMethod -trimprefix=fb"; DO NOT EDIT.

package slackdump

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fbAuthTestContext-0]
	_ = x[fbGetConversationHistoryContext-1]
	_ = x[fbGetConversationRepliesContext-2]
	_ = x[fbGetConversationsContext-3]
	_ = x[fbGetStarredContext-4]
	_ = x[fbGetUsersPaginated-5]
	_ = x[fbListBookmarks-6]
	_ = x[fbGetConversationInfo-7]
	_ = x[fbGetUsersInConversation-8]
	_ = x[fbGetFile-9]
	_ = x[fbGetUsersContext-10]
	_ = x[fbGetEmojiContext-11]
}

const _fallbackMethod_name = "AuthTestContextGetConversationHistoryContextGetConversationRepliesContextGetConversationsContextGetStarredContextGetUsersPaginatedListBookmarksGetConversationInfoGetUsersInConversationGetFileGetUsersContextGetEmojiContext"

var _fallbackMethod_index = [...]uint8{0, 15, 44, 73, 96, 113, 130, 143, 162, 184, 191, 206, 221}

func (i fallbackMethod) String() string {
	if i < 0 || i >= fallbackMethod(len(_fallbackMethod_index)-1) {
		return "fallbackMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fallbackMethod_name[_fallbackMethod_index[i]:_fallbackMethod_index[i+1]]
}
