-- +goose Up
-- +goose StatementBegin
CREATE TABLE SESSION
(
    ID              BIGSERIAL PRIMARY KEY,
    CREATED_AT      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PAR_SESSION_ID  BIGINT,
    FROM_TS         TIMESTAMPTZ,
    TO_TS           TIMESTAMPTZ,
    FINISHED        BOOLEAN     NOT NULL DEFAULT FALSE,
    FILES_ENABLED   BOOLEAN     NOT NULL DEFAULT FALSE,
    AVATARS_ENABLED BOOLEAN     NOT NULL DEFAULT FALSE,
    MODE            TEXT        NOT NULL,
    ARGS            TEXT
);

CREATE TABLE CHUNK
(
    ID           BIGSERIAL PRIMARY KEY,
    CREATED_AT   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIX_TS      BIGINT      NOT NULL,
    SESSION_ID   BIGINT      NOT NULL,
    TYPE_ID      SMALLINT    NOT NULL,
    NUM_REC      INTEGER     NOT NULL DEFAULT 0,
    FINAL        BOOLEAN     NOT NULL DEFAULT FALSE,
    CHANNEL_ID   TEXT,
    SEARCH_QUERY TEXT,
    THREAD_ONLY  BOOLEAN,
    FOREIGN KEY (SESSION_ID) REFERENCES SESSION (ID) ON DELETE RESTRICT
);

CREATE TABLE MESSAGE
(
    ID           BIGINT      NOT NULL,
    CHUNK_ID     BIGINT      NOT NULL,
    LOAD_DTTM    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANNEL_ID   TEXT        NOT NULL,
    TS           TEXT        NOT NULL,
    PARENT_ID    BIGINT,
    THREAD_TS    TEXT,
    LATEST_REPLY TEXT,
    IS_PARENT    BOOLEAN     NOT NULL DEFAULT FALSE,
    IDX          INTEGER     NOT NULL,
    NUM_FILES    INTEGER     NOT NULL DEFAULT 0,
    TXT          TEXT,
    DATA         BYTEA       NOT NULL,
    PRIMARY KEY (ID, CHUNK_ID),
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE CHANNEL
(
    ID        TEXT        NOT NULL,
    CHUNK_ID  BIGINT      NOT NULL,
    LOAD_DTTM TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME      TEXT,
    IDX       INTEGER     NOT NULL,
    DATA      BYTEA       NOT NULL,
    PRIMARY KEY (ID, CHUNK_ID),
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE FILE
(
    ID         TEXT        NOT NULL,
    CHUNK_ID   BIGINT      NOT NULL,
    LOAD_DTTM  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANNEL_ID TEXT        NOT NULL,
    MESSAGE_ID BIGINT,
    THREAD_ID  BIGINT,
    IDX        INTEGER     NOT NULL,
    MODE       TEXT        NOT NULL,
    FILENAME   TEXT,
    URL        TEXT,
    DATA       BYTEA       NOT NULL,
    SIZE       BIGINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (ID, CHUNK_ID),
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE WORKSPACE
(
    ID            BIGSERIAL PRIMARY KEY,
    CHUNK_ID      BIGINT      NOT NULL,
    LOAD_DTTM     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TEAM          TEXT        NOT NULL,
    USERNAME      TEXT,
    TEAM_ID       TEXT        NOT NULL,
    USER_ID       TEXT        NOT NULL,
    ENTERPRISE_ID TEXT,
    URL           TEXT        NOT NULL,
    DATA          BYTEA       NOT NULL,
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE S_USER
(
    ID        TEXT        NOT NULL,
    CHUNK_ID  BIGINT      NOT NULL,
    LOAD_DTTM TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IDX       INTEGER     NOT NULL,
    USERNAME  TEXT        NOT NULL,
    DATA      BYTEA       NOT NULL,
    PRIMARY KEY (ID, CHUNK_ID),
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE CHANNEL_USER
(
    CHANNEL_ID TEXT        NOT NULL,
    USER_ID    TEXT        NOT NULL,
    CHUNK_ID   BIGINT      NOT NULL,
    LOAD_DTTM  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IDX        INTEGER     NOT NULL,
    PRIMARY KEY (CHANNEL_ID, USER_ID, CHUNK_ID),
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE SEARCH_MESSAGE
(
    ID           BIGSERIAL PRIMARY KEY,
    CHUNK_ID     BIGINT      NOT NULL,
    LOAD_DTTM    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANNEL_ID   TEXT        NOT NULL,
    CHANNEL_NAME TEXT,
    TS           TEXT        NOT NULL,
    TXT          TEXT,
    IDX          INTEGER     NOT NULL,
    DATA         BYTEA       NOT NULL,
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE SEARCH_FILE
(
    ID        BIGSERIAL PRIMARY KEY,
    CHUNK_ID  BIGINT      NOT NULL,
    LOAD_DTTM TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FILE_ID   TEXT        NOT NULL,
    IDX       INTEGER     NOT NULL,
    DATA      BYTEA       NOT NULL,
    FOREIGN KEY (CHUNK_ID) REFERENCES CHUNK (ID) ON DELETE CASCADE
);

CREATE TABLE TYPES
(
    ID   SMALLINT PRIMARY KEY,
    NAME TEXT NOT NULL
);

INSERT INTO TYPES (ID, NAME) VALUES
 (0, 'MESSAGES'),
 (1, 'THREAD_MESSAGES'),
 (2, 'FILES'),
 (3, 'USERS'),
 (4, 'CHANNELS'),
 (5, 'CHANNEL_INFO'),
 (6, 'WORKSPACE_INFO'),
 (7, 'CHANNEL_USERS'),
 (8, 'STARRED_ITEMS'),
 (9, 'BOOKMARKS'),
 (10, 'SEARCH_MESSAGES'),
 (11, 'SEARCH_FILES');

CREATE TABLE ALIAS
(
    CHANNEL_ID TEXT PRIMARY KEY,
    ALIAS      TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX MESSAGE_CHUNK_ID_IDX ON MESSAGE (CHUNK_ID);
CREATE INDEX MESSAGE_I1 ON MESSAGE (CHANNEL_ID, CHUNK_ID, IS_PARENT);
CREATE INDEX MESSAGE_I2 ON MESSAGE (CHANNEL_ID, PARENT_ID);
CREATE INDEX MESSAGE_I3 ON MESSAGE (IS_PARENT, LATEST_REPLY);
CREATE INDEX CHANNEL_CHUNK_ID_IDX ON CHANNEL (CHUNK_ID);
CREATE INDEX FILE_CHUNK_ID_IDX ON FILE (CHUNK_ID);
CREATE INDEX FILE_I1 ON FILE (MESSAGE_ID, THREAD_ID);
CREATE INDEX FILE_ID_SIZE_IDX ON FILE (ID, SIZE);
CREATE INDEX S_USER_CHUNK_ID_IDX ON S_USER (CHUNK_ID);
CREATE INDEX CHANNEL_USER_I1 ON CHANNEL_USER (USER_ID, CHUNK_ID);
CREATE INDEX CHANNEL_USER_CHUNK_ID_IDX ON CHANNEL_USER (CHUNK_ID);
CREATE INDEX SEARCH_MSG_CHUNK_ID_IDX ON SEARCH_MESSAGE (CHUNK_ID);
CREATE INDEX SEARCH_FILE_I1 ON SEARCH_FILE (FILE_ID, CHUNK_ID);
CREATE INDEX SEARCH_FILE_CHUNK_ID_IDX ON SEARCH_FILE (CHUNK_ID);
CREATE INDEX CHUNK_I1 ON CHUNK (CHANNEL_ID, SESSION_ID, TYPE_ID, FINAL);

CREATE VIEW V_CHANNEL_THREADS AS
WITH MSG AS (
    SELECT M1.CHANNEL_ID, M1.IS_PARENT, C1.SESSION_ID
    FROM MESSAGE M1
    JOIN CHUNK C1 ON C1.ID = M1.CHUNK_ID
    WHERE C1.TYPE_ID = 0
      AND (M1.LATEST_REPLY != '0000000000.000000' OR M1.LATEST_REPLY IS NULL)
      AND M1.IS_PARENT
)
SELECT C.SESSION_ID, C.CHANNEL_ID, COUNT(M.IS_PARENT)::BIGINT AS THREADS
FROM CHUNK C
LEFT JOIN MSG M ON M.CHANNEL_ID = C.CHANNEL_ID AND M.SESSION_ID = C.SESSION_ID
WHERE C.TYPE_ID = 0 AND C.FINAL
GROUP BY C.SESSION_ID, C.CHANNEL_ID;

CREATE VIEW V_CHANNEL_THREAD_COUNT AS
SELECT C.SESSION_ID, M.CHANNEL_ID, COUNT(DISTINCT M.PARENT_ID)::BIGINT AS PARENT_COUNT
FROM CHUNK C
JOIN MESSAGE M ON C.ID = M.CHUNK_ID
WHERE C.TYPE_ID = 1
GROUP BY C.SESSION_ID, M.CHANNEL_ID;

CREATE VIEW V_UNFINISHED_CHANNELS AS
SELECT CT.SESSION_ID,
       CT.CHANNEL_ID,
       CT.THREADS - COALESCE(TC.PARENT_COUNT, 0) AS REF_COUNT
FROM V_CHANNEL_THREADS CT
LEFT JOIN V_CHANNEL_THREAD_COUNT TC
  ON CT.CHANNEL_ID = TC.CHANNEL_ID AND CT.SESSION_ID = TC.SESSION_ID;

CREATE VIEW V_ORPHAN_THREADS AS
WITH UNFINISHED_THREADS AS (
    SELECT CHANNEL_ID FROM V_UNFINISHED_CHANNELS WHERE REF_COUNT > 0
),
DIFF AS (
    SELECT M.CHANNEL_ID, M.THREAD_TS
    FROM MESSAGE M
    JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
    WHERE IS_PARENT = TRUE
    EXCEPT
    SELECT DISTINCT M.CHANNEL_ID, M.THREAD_TS
    FROM MESSAGE M
    JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
    JOIN CHUNK C ON C.ID = M.CHUNK_ID
    WHERE C.TYPE_ID = 1
)
SELECT * FROM DIFF;

CREATE VIEW V_EMPTY_THREADS AS
SELECT C.SESSION_ID,
       M.CHUNK_ID,
       M.CHANNEL_ID,
       M.THREAD_TS,
       'archives/' || M.CHANNEL_ID || '/p' || CAST(M.PARENT_ID AS TEXT) AS PATH
FROM MESSAGE M
JOIN CHUNK C ON M.CHUNK_ID = C.ID
WHERE M.IS_PARENT = TRUE
  AND M.LATEST_REPLY = '0000000000.000000';

CREATE VIEW V_THREAD_ONLY_THREADS AS
WITH MSG AS (
    SELECT ID, CHANNEL_ID, THREAD_TS, IS_PARENT, CHUNK_ID
    FROM MESSAGE
    WHERE IS_PARENT = TRUE
    EXCEPT
    SELECT ID, CHANNEL_ID, THREAD_TS, IS_PARENT, CHUNK_ID
    FROM MESSAGE
    WHERE LATEST_REPLY = '0000000000.000000' AND IS_PARENT = TRUE
)
SELECT C.SESSION_ID,
       M.CHANNEL_ID,
       M.THREAD_TS,
       COUNT(M.IS_PARENT)::BIGINT AS PARTS
FROM MSG M
JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE IS_PARENT = TRUE
  AND C.TYPE_ID = 1
  AND C.THREAD_ONLY = TRUE
  AND EXISTS (
      SELECT 1
      FROM CHUNK MC
      JOIN MESSAGE MM ON MM.CHUNK_ID = MC.ID
      WHERE MC.CHANNEL_ID = C.CHANNEL_ID
        AND MC.TYPE_ID = C.TYPE_ID
        AND MC.THREAD_ONLY = TRUE
        AND MC.SESSION_ID = C.SESSION_ID
        AND MM.THREAD_TS = M.THREAD_TS
        AND MC.FINAL
  )
GROUP BY C.SESSION_ID, M.CHANNEL_ID, M.THREAD_TS;

CREATE VIEW V_LATEST_MESSAGE AS
SELECT M.CHANNEL_ID, M.TS, M.ID
FROM MESSAGE M
JOIN CHUNK C ON M.CHUNK_ID = C.ID
WHERE C.TYPE_ID = 0
  AND (M.CHANNEL_ID, M.ID) IN (
      SELECT M2.CHANNEL_ID, MAX(M2.ID)
      FROM MESSAGE M2
      JOIN CHUNK C2 ON C2.ID = M2.CHUNK_ID
      WHERE C2.TYPE_ID = 0
      GROUP BY M2.CHANNEL_ID
  );

CREATE VIEW V_LATEST_THREAD AS
SELECT DISTINCT M.CHANNEL_ID, M.THREAD_TS, M.TS, M.PARENT_ID, M.ID
FROM MESSAGE M
JOIN CHUNK C ON M.CHUNK_ID = C.ID
WHERE C.TYPE_ID = 1
  AND (M.CHANNEL_ID, M.THREAD_TS, M.ID) IN (
      SELECT M2.CHANNEL_ID, M2.THREAD_TS, MAX(M2.ID)
      FROM MESSAGE M2
      JOIN CHUNK C2 ON C2.ID = M2.CHUNK_ID
      WHERE C2.TYPE_ID = 1
      GROUP BY M2.CHANNEL_ID, M2.THREAD_TS
  );
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW IF EXISTS V_LATEST_THREAD;
DROP VIEW IF EXISTS V_LATEST_MESSAGE;
DROP VIEW IF EXISTS V_THREAD_ONLY_THREADS;
DROP VIEW IF EXISTS V_EMPTY_THREADS;
DROP VIEW IF EXISTS V_ORPHAN_THREADS;
DROP VIEW IF EXISTS V_UNFINISHED_CHANNELS;
DROP VIEW IF EXISTS V_CHANNEL_THREAD_COUNT;
DROP VIEW IF EXISTS V_CHANNEL_THREADS;
DROP TABLE IF EXISTS ALIAS;
DROP TABLE IF EXISTS TYPES;
DROP TABLE IF EXISTS SEARCH_FILE;
DROP TABLE IF EXISTS SEARCH_MESSAGE;
DROP TABLE IF EXISTS CHANNEL_USER;
DROP TABLE IF EXISTS S_USER;
DROP TABLE IF EXISTS WORKSPACE;
DROP TABLE IF EXISTS FILE;
DROP TABLE IF EXISTS CHANNEL;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CHUNK;
DROP TABLE IF EXISTS SESSION;
-- +goose StatementEnd
