// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeValue-1]
	_ = x[TypeCookieFile-2]
	_ = x[TypeBrowser-3]
	_ = x[TypeRod-4]
}

const _Type_name = "InvalidValueCookie FileEZ-Login 3000EZ-Login 3001"

var _Type_index = [...]uint8{0, 7, 12, 23, 36, 49}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
