// Code generated by "stringer -type=ResultType -trimprefix=RT"; DO NOT EDIT.

package stream

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RTMain-0]
	_ = x[RTChannel-1]
	_ = x[RTThread-2]
	_ = x[RTChannelInfo-3]
	_ = x[RTChannelUsers-4]
	_ = x[RTSearch-5]
}

const _ResultType_name = "MainChannelThreadChannelInfoChannelUsersSearch"

var _ResultType_index = [...]uint8{0, 4, 11, 17, 28, 40, 46}

func (i ResultType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResultType_index)-1 {
		return "ResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResultType_name[_ResultType_index[idx]:_ResultType_index[idx+1]]
}
