// Copyright (c) 2021-2026 Rustam Gilyazov and Contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// Code generated by "stringer -type=ResultType -trimprefix=RT"; DO NOT EDIT.

package stream

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RTMain-0]
	_ = x[RTChannel-1]
	_ = x[RTThread-2]
	_ = x[RTChannelInfo-3]
	_ = x[RTChannelUsers-4]
	_ = x[RTSearch-5]
}

const _ResultType_name = "MainChannelThreadChannelInfoChannelUsersSearch"

var _ResultType_index = [...]uint8{0, 4, 11, 17, 28, 40, 46}

func (i ResultType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResultType_index)-1 {
		return "ResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResultType_name[_ResultType_index[idx]:_ResultType_index[idx+1]]
}
