-- +goose Up
-- +goose StatementBegin
ALTER TABLE CHUNK
    ADD COLUMN THREAD_ONLY BOOLEAN;

DROP VIEW IF EXISTS V_CHANNEL_THREADS;
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE IS_PARENT = TRUE
             EXCEPT
             SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE IS_PARENT = TRUE
  AND (C.TYPE_ID = 0 OR (C.TYPE_ID = 1 AND C.THREAD_ONLY))
  AND EXISTS (
    -- CHANNEL MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.SESSION_ID = C.SESSION_ID
      AND FINAL)
GROUP BY M.CHANNEL_ID;

DROP VIEW IF EXISTS V_THREAD_COUNT;
CREATE VIEW IF NOT EXISTS V_THREAD_COUNT AS
WITH COUNTER AS (SELECT C.SESSION_ID,
                        M.CHANNEL_ID,
                        CASE
                            WHEN C.THREAD_ONLY AND M.IS_PARENT THEN 1
                            ELSE 0
                            END THREAD_ONLY_PARENT,
                        M.PARENT_ID
                 FROM CHUNK C
                          JOIN MESSAGE M ON C.ID = M.CHUNK_ID
                 WHERE C.TYPE_ID = 1)
SELECT SESSION_ID
     , CHANNEL_ID
     , COUNT(DISTINCT PARENT_ID) + SUM(THREAD_ONLY_PARENT) PARENT_COUNT
FROM COUNTER
GROUP BY SESSION_ID, CHANNEL_ID;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP VIEW IF EXISTS V_THREAD_COUNT;
-- V_THREAD_COUNT HAS THE COUNT OF ACTUALLY DOWNLOADED THREADS.
CREATE VIEW IF NOT EXISTS V_THREAD_COUNT AS
SELECT C.SESSION_ID
     , M.CHANNEL_ID
     , COUNT(DISTINCT M.PARENT_ID) PARENT_COUNT
FROM CHUNK C
         JOIN MESSAGE M ON C.ID = M.CHUNK_ID
WHERE C.TYPE_ID = 1
GROUP BY C.SESSION_ID, M.CHANNEL_ID;

DROP VIEW IF EXISTS V_CHANNEL_THREADS;
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE IS_PARENT = TRUE
             EXCEPT
             SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE IS_PARENT = TRUE
  AND C.TYPE_ID = 0
  AND EXISTS (
    -- CHANNEL MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.SESSION_ID = C.SESSION_ID
      AND FINAL)
GROUP BY M.CHANNEL_ID;

ALTER TABLE CHUNK
    DROP COLUMN THREAD_ONLY;
-- +goose StatementEnd
