-- +goose Up
-- +goose StatementBegin
ALTER TABLE CHUNK
    ADD COLUMN THREAD_ONLY BOOLEAN;

DROP VIEW IF EXISTS V_THREAD_COUNT;
-- V_CHANNEL_THREAD_COUNT HAS THE COUNT OF ACTUALLY DOWNLOADED THREADS FOR THE CHANNEL.
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREAD_COUNT AS
SELECT C.SESSION_ID
     , M.CHANNEL_ID
     , COUNT(DISTINCT M.PARENT_ID) PARENT_COUNT
FROM CHUNK C
         JOIN MESSAGE M ON C.ID = M.CHUNK_ID
WHERE C.TYPE_ID = 1
GROUP BY C.SESSION_ID, M.CHANNEL_ID;

DROP VIEW IF EXISTS V_UNFINISHED_THREADS;
-- V_UNFINISHED_CHANNELS IS THE COUNT OF UNFINISHED THREADS FOR EACH CHANNEL.
-- SUCCESSFUL EXPORT MUST HAVE REF_COUNT = 0 FOR ALL CHANNELS.
CREATE VIEW IF NOT EXISTS V_UNFINISHED_CHANNELS AS
SELECT CT.SESSION_ID
     , CT.CHANNEL_ID
     , CT.THREADS - COALESCE(TC.PARENT_COUNT, 0) AS REF_COUNT
FROM V_CHANNEL_THREADS AS CT
         LEFT JOIN V_CHANNEL_THREAD_COUNT TC
                   ON (CT.CHANNEL_ID = TC.CHANNEL_ID
                       AND CT.SESSION_ID = TC.SESSION_ID);

DROP VIEW IF EXISTS V_ORPHAN_THREADS;
-- ORPHAN THREADS FINDS ALL THE THREADS WHICH HAVE A PARENT, BUT NOT A CHILD
-- (THREAD_MESSAGES HAS NOT (YET) FETCHED THE THREAD.  IN THE NORMAL CONDITIONS
-- ON A COMPLETED DUMP, ALL COUNTS FOR A SESSION SHOULD BE 0.
CREATE VIEW IF NOT EXISTS V_ORPHAN_THREADS AS
WITH UNFINISHED_THREADS AS (SELECT CHANNEL_ID
                            FROM V_UNFINISHED_CHANNELS
                            WHERE REF_COUNT > 0),
     DIFF AS (SELECT M.CHANNEL_ID, M.THREAD_TS
              FROM MESSAGE M
                       JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
              WHERE IS_PARENT = TRUE
              EXCEPT
              SELECT DISTINCT M.CHANNEL_ID, M.THREAD_TS
              FROM MESSAGE M
                       JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
                       JOIN CHUNK C ON C.ID = M.CHUNK_ID
              WHERE C.TYPE_ID = 1
              GROUP BY M.CHANNEL_ID, M.THREAD_TS)
SELECT *
FROM DIFF;


-- V_THREAD_ONLY_THREADS CONTAINS PART COUNT FOR ALL THREAD FOR THREAD_ONLY CHUNKS.
-- IT IS LIKE V_CHANNEL_THREADS, BUT FOR THREAD-ONLY CHUNKS.
CREATE VIEW IF NOT EXISTS V_THREAD_ONLY_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, THREAD_TS, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE IS_PARENT = TRUE
             EXCEPT
             SELECT ID, CHANNEL_ID, THREAD_TS, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, M.THREAD_TS, SUM(M.IS_PARENT) PARTS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE IS_PARENT = TRUE
  AND (C.TYPE_ID = 1 AND C.THREAD_ONLY = TRUE)
  AND EXISTS (
    -- THREAD MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
             JOIN MESSAGE MM ON MM.CHUNK_ID = MC.ID
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.THREAD_ONLY = TRUE
      AND MC.SESSION_ID = C.SESSION_ID
      AND MM.THREAD_TS = M.THREAD_TS
      AND MC.FINAL)
GROUP BY C.SESSION_ID, M.CHANNEL_ID, M.THREAD_TS;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW IF EXISTS V_THREAD_ONLY_THREADS;

DROP VIEW IF EXISTS V_CHANNEL_THREAD_COUNT;
-- V_THREAD_COUNT HAS THE COUNT OF ACTUALLY DOWNLOADED THREADS.
CREATE VIEW IF NOT EXISTS V_THREAD_COUNT AS
SELECT C.SESSION_ID
     , M.CHANNEL_ID
     , COUNT(DISTINCT M.PARENT_ID) PARENT_COUNT
FROM CHUNK C
         JOIN MESSAGE M ON C.ID = M.CHUNK_ID
WHERE C.TYPE_ID = 1
GROUP BY C.SESSION_ID, M.CHANNEL_ID;

DROP VIEW IF EXISTS V_UNFINISHED_CHANNELS;
-- V_UNFINISHED_THREADS IS THE COUNT OF UNFINISHED THREADS FOR EACH CHANNEL.
-- SUCCESSFUL EXPORT MUST HAVE REF_COUNT = 0 FOR ALL CHANNELS.
CREATE VIEW IF NOT EXISTS V_UNFINISHED_THREADS AS
SELECT CT.SESSION_ID
     , CT.CHANNEL_ID
     , CT.THREADS - COALESCE(TC.PARENT_COUNT, 0) AS REF_COUNT
FROM V_CHANNEL_THREADS AS CT
         LEFT JOIN V_THREAD_COUNT TC
                   ON (CT.CHANNEL_ID = TC.CHANNEL_ID
                       AND CT.SESSION_ID = TC.SESSION_ID);

DROP VIEW IF EXISTS V_ORPHAN_THREADS;
-- ORPHAN THREADS FINDS ALL THE THREADS WHICH HAVE A PARENT, BUT NOT A CHILD
-- (THREAD_MESSAGES HAS NOT (YET) FETCHED THE THREAD.  IN THE NORMAL CONDITIONS
-- ON A COMPLETED DUMP, ALL COUNTS FOR A SESSION SHOULD BE 0.
CREATE VIEW IF NOT EXISTS V_ORPHAN_THREADS AS
WITH UNFINISHED_THREADS AS (SELECT CHANNEL_ID
                            FROM V_UNFINISHED_THREADS
                            WHERE REF_COUNT > 0),
     DIFF AS (SELECT M.CHANNEL_ID, M.THREAD_TS
              FROM MESSAGE M
                       JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
              WHERE IS_PARENT = TRUE
              EXCEPT
              SELECT DISTINCT M.CHANNEL_ID, M.THREAD_TS
              FROM MESSAGE M
                       JOIN UNFINISHED_THREADS P ON P.CHANNEL_ID = M.CHANNEL_ID
                       JOIN CHUNK C ON C.ID = M.CHUNK_ID
              WHERE C.TYPE_ID = 1
              GROUP BY M.CHANNEL_ID, M.THREAD_TS)
SELECT *
FROM DIFF;



ALTER TABLE CHUNK
    DROP COLUMN THREAD_ONLY;
-- +goose StatementEnd
