-- +goose Up
-- +goose StatementBegin
DROP VIEW IF EXISTS V_CHANNEL_THREADS;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (
  SELECT M1.CHANNEL_ID, M1.IS_PARENT, C1.SESSION_ID, C1.TYPE_ID
  FROM MESSAGE M1
  JOIN CHUNK C1 ON C1.ID = M1.CHUNK_ID AND C1.CHANNEL_ID = M1.CHANNEL_ID
  WHERE C1.TYPE_ID =0
	AND (M1.LATEST_REPLY != '0000000000.000000' OR M1.LATEST_REPLY IS NULL) AND M1.IS_PARENT
)
SELECT C.SESSION_ID, C.CHANNEL_ID, COALESCE(SUM(M.IS_PARENT),0) THREADS
FROM CHUNK AS C
LEFT JOIN MSG AS M ON M.CHANNEL_ID = C.CHANNEL_ID AND M.SESSION_ID = C.SESSION_ID AND C.TYPE_ID = M.TYPE_ID
WHERE C.TYPE_ID=0
	AND C.FINAL
GROUP BY C.SESSION_ID, C.CHANNEL_ID;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW IF EXISTS V_CHANNEL_THREADS;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             EXCEPT
             SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE 1 = 1 
  AND C.TYPE_ID = 0
  AND EXISTS (
    -- CHANNEL MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.SESSION_ID = C.SESSION_ID
      AND FINAL)
GROUP BY M.CHANNEL_ID
-- +goose StatementEnd
