-- +goose Up
-- +goose StatementBegin
DROP VIEW IF EXISTS V_CHANNEL_THREADS;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             EXCEPT
             SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE 1 = 1 
  AND C.TYPE_ID = 0
  AND EXISTS (
    -- CHANNEL MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.SESSION_ID = C.SESSION_ID
      AND FINAL)
GROUP BY M.CHANNEL_ID
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW IF EXISTS V_CHANNEL_THREADS;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE VIEW IF NOT EXISTS V_CHANNEL_THREADS AS
WITH MSG AS (SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE IS_PARENT = TRUE
             EXCEPT
             SELECT ID, CHANNEL_ID, IS_PARENT, CHUNK_ID
             FROM MESSAGE
             WHERE LATEST_REPLY = '0000000000.000000' -- EMPTY THREADS
               AND IS_PARENT = TRUE)
SELECT C.SESSION_ID, M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MSG M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
WHERE IS_PARENT = TRUE
  AND C.TYPE_ID = 0
  AND EXISTS (
    -- CHANNEL MUST BE FINISHED
    SELECT 1
    FROM CHUNK MC
    WHERE MC.CHANNEL_ID = C.CHANNEL_ID
      AND MC.TYPE_ID = C.TYPE_ID
      AND MC.SESSION_ID = C.SESSION_ID
      AND FINAL)
GROUP BY M.CHANNEL_ID;
-- +goose StatementEnd
