-- +goose Up
-- +goose StatementBegin
DROP VIEW IF EXISTS V_EMPTY_THREADS;
-- V_EMPTY_THREADS SHOWS ALL EMPTY THREADS (THREADS THAT HAVE PARENT MESSAGE,
-- BUT NO MESSAGES IN THEM).
CREATE VIEW IF NOT EXISTS V_EMPTY_THREADS AS
SELECT C.SESSION_ID
     , M.CHUNK_ID
     , M.CHANNEL_ID
     , M.THREAD_TS
     , 'archives/' || M.CHANNEL_ID || '/p' || cast(M.PARENT_ID AS TEXT) as PATH
FROM MESSAGE M
         JOIN CHUNK C ON M.CHUNK_ID = C.ID
WHERE M.IS_PARENT = TRUE
  AND M.LATEST_REPLY = '0000000000.000000';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW IF EXISTS V_EMPTY_THREADS;
-- V_EMPTY_THREADS SHOWS ALL EMPTY THREADS (THREADS THAT HAVE PARENT MESSAGE,
-- BUT NO MESSAGES IN THEM).
CREATE VIEW IF NOT EXISTS V_EMPTY_THREADS AS
SELECT M.SESSION_ID
     , M.CHUNK_ID
     , M.CHANNEL_ID
     , M.THREAD_TS
     , 'archives/' || M.CHANNEL_ID || '/p' || cast(M.PARENT_ID AS TEXT) as PATH
FROM MESSAGE M
         JOIN CHUNK C ON M.CHUNK_ID = C.ID
WHERE M.IS_PARENT = TRUE
  AND M.LATEST_REPLY = '0000000000.000000';
-- +goose StatementEnd

