// Code generated by "stringer -type=EventType -trimprefix=E"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMessages-0]
	_ = x[EThreadMessages-1]
	_ = x[EFiles-2]
}

const _EventType_name = "MessagesThreadMessagesFiles"

var _EventType_index = [...]uint8{0, 8, 22, 27}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
