// Copyright (c) 2021-2026 Rustam Gilyazov and Contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// Code generated by "stringer -type dumptype -trimprefix=dt"; DO NOT EDIT.

package format

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dtUnknown-0]
	_ = x[dtConversation-1]
	_ = x[dtChannels-2]
	_ = x[dtUsers-3]
}

const _dumptype_name = "UnknownConversationChannelsUsers"

var _dumptype_index = [...]uint8{0, 7, 19, 27, 32}

func (i dumptype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_dumptype_index)-1 {
		return "dumptype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dumptype_name[_dumptype_index[idx]:_dumptype_index[idx+1]]
}
