-- +goose Up
-- +goose StatementBegin
CREATE VIEW CHANNEL_THREADS AS
SELECT M.CHANNEL_ID, SUM(M.IS_PARENT) THREADS
FROM MESSAGE M
         JOIN CHUNK C ON C.ID = M.CHUNK_ID
GROUP BY M.CHANNEL_ID;

CREATE VIEW THREAD_COUNT AS
SELECT C.SESSION_ID, M.CHANNEL_ID, COUNT(DISTINCT M.PARENT_ID) PARENT_COUNT
FROM CHUNK C
         JOIN MESSAGE M ON C.ID = M.CHUNK_ID
WHERE C.TYPE_ID = 1
GROUP BY C.SESSION_ID, M.CHANNEL_ID;

CREATE VIEW REF_COUNT AS
SELECT CT.CHANNEL_ID, CT.THREADS - TC.PARENT_COUNT REF_COUNT
FROM CHANNEL_THREADS AS CT
         JOIN THREAD_COUNT TC ON CT.CHANNEL_ID = TC.CHANNEL_ID;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP VIEW REF_COUNT;
DROP VIEW THREAD_COUNT;
DROP VIEW CHANNEL_THREADS;
-- +goose StatementEnd
