// Copyright (c) 2021-2026 Rustam Gilyazov and Contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// Code generated by "stringer -type=datafmt -trimprefix=F"; DO NOT EDIT.

package convertcmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fdump-0]
	_ = x[Fexport-1]
	_ = x[Fchunk-2]
	_ = x[Fdatabase-3]
}

const _datafmt_name = "dumpexportchunkdatabase"

var _datafmt_index = [...]uint8{0, 4, 10, 15, 23}

func (i datafmt) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_datafmt_index)-1 {
		return "datafmt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _datafmt_name[_datafmt_index[idx]:_datafmt_index[idx+1]]
}
