// Code generated by "stringer -type StatusCode -linecomment"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SNoError-0]
	_ = x[SGenericError-1]
	_ = x[SHelpRequested-2]
	_ = x[SInvalidParameters-3]
	_ = x[SAuthError-4]
	_ = x[SApplicationError-5]
	_ = x[SWorkspaceError-6]
	_ = x[SCacheError-7]
	_ = x[SUserError-8]
}

const _StatusCode_name = "No ErrorGeneric ErrorHelp RequestedInvalid ParametersAuthentication ErrorApplication ErrorWorkspace ErrorCache ErrorUser Error"

var _StatusCode_index = [...]uint8{0, 8, 21, 35, 53, 73, 90, 105, 116, 126}

func (i StatusCode) String() string {
	if i >= StatusCode(len(_StatusCode_index)-1) {
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[i]:_StatusCode_index[i+1]]
}
