// Copyright (c) 2021-2026 Rustam Gilyazov and Contributors.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// Code generated by MockGen. DO NOT EDIT.
// Source: emoji.go
//
// Generated by this command:
//
//	mockgen -source emoji.go -destination emoji_mock_test.go -package emojidl
//

// Package emojidl is a generated GoMock package.
package emojidl

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmojiDumper is a mock of EmojiDumper interface.
type MockEmojiDumper struct {
	ctrl     *gomock.Controller
	recorder *MockEmojiDumperMockRecorder
	isgomock struct{}
}

// MockEmojiDumperMockRecorder is the mock recorder for MockEmojiDumper.
type MockEmojiDumperMockRecorder struct {
	mock *MockEmojiDumper
}

// NewMockEmojiDumper creates a new mock instance.
func NewMockEmojiDumper(ctrl *gomock.Controller) *MockEmojiDumper {
	mock := &MockEmojiDumper{ctrl: ctrl}
	mock.recorder = &MockEmojiDumperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmojiDumper) EXPECT() *MockEmojiDumperMockRecorder {
	return m.recorder
}

// GetEmojiContext mocks base method.
func (m *MockEmojiDumper) GetEmojiContext(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmojiContext", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmojiContext indicates an expected call of GetEmojiContext.
func (mr *MockEmojiDumperMockRecorder) GetEmojiContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmojiContext", reflect.TypeOf((*MockEmojiDumper)(nil).GetEmojiContext), ctx)
}
