// Code generated by MockGen. DO NOT EDIT.
// Source: emoji.go
//
// Generated by this command:
//
//	mockgen -source emoji.go -destination emoji_mock_test.go -package emojidl
//

// Package emojidl is a generated GoMock package.
package emojidl

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmojiDumper is a mock of EmojiDumper interface.
type MockEmojiDumper struct {
	ctrl     *gomock.Controller
	recorder *MockEmojiDumperMockRecorder
	isgomock struct{}
}

// MockEmojiDumperMockRecorder is the mock recorder for MockEmojiDumper.
type MockEmojiDumperMockRecorder struct {
	mock *MockEmojiDumper
}

// NewMockEmojiDumper creates a new mock instance.
func NewMockEmojiDumper(ctrl *gomock.Controller) *MockEmojiDumper {
	mock := &MockEmojiDumper{ctrl: ctrl}
	mock.recorder = &MockEmojiDumperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmojiDumper) EXPECT() *MockEmojiDumperMockRecorder {
	return m.recorder
}

// DumpEmojis mocks base method.
func (m *MockEmojiDumper) DumpEmojis(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpEmojis", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpEmojis indicates an expected call of DumpEmojis.
func (mr *MockEmojiDumperMockRecorder) DumpEmojis(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpEmojis", reflect.TypeOf((*MockEmojiDumper)(nil).DumpEmojis), ctx)
}
