= BenchmarkTs2Int

== i7-4600U
=== 32bit

[source]
---
PS C:\slackdump\internal\fasttime>go test . -bench ".*" -count=10
goos: windows
goarch: 386
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
BenchmarkTs2Int-4        3395229               342.9 ns/op
BenchmarkTs2Int-4        3516256               330.3 ns/op
BenchmarkTs2Int-4        3571240               334.7 ns/op
BenchmarkTs2Int-4        3588696               332.4 ns/op
BenchmarkTs2Int-4        3579144               330.6 ns/op
BenchmarkTs2Int-4        3565935               331.5 ns/op
BenchmarkTs2Int-4        3505794               333.7 ns/op
BenchmarkTs2Int-4        3601692               331.8 ns/op
BenchmarkTs2Int-4        3552079               332.3 ns/op
BenchmarkTs2Int-4        3594452               334.0 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  15.460s
---

=== 64bit

[source]
---   
PS C:\slackdump\internal\fasttime>go test . -bench=".*" -count=10
goos: windows
goarch: amd64
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
BenchmarkTs2Int-4       24260755                46.94 ns/op
BenchmarkTs2Int-4       22409967                46.41 ns/op
BenchmarkTs2Int-4       23303821                47.15 ns/op
BenchmarkTs2Int-4       22653648                46.85 ns/op
BenchmarkTs2Int-4       23203335                46.85 ns/op
BenchmarkTs2Int-4       23275254                46.59 ns/op
BenchmarkTs2Int-4       23464814                46.64 ns/op
BenchmarkTs2Int-4       22861932                47.32 ns/op
BenchmarkTs2Int-4       22373408                46.77 ns/op
BenchmarkTs2Int-4       23907906                46.81 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  12.546s
---

== i9-9880H @ 2.30GHz
== 64bit

[source]
---
[3:30:15] 0:slackdump/internal/fasttime (v3-tests)> go test . -bench '.*' -count=10
goos: darwin
goarch: amd64
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkTs2Int-16      29724420                34.15 ns/op
BenchmarkTs2Int-16      30925324                34.26 ns/op
BenchmarkTs2Int-16      29584566                33.91 ns/op
BenchmarkTs2Int-16      35253584                34.05 ns/op
BenchmarkTs2Int-16      29480674                35.25 ns/op
BenchmarkTs2Int-16      29552312                34.18 ns/op
BenchmarkTs2Int-16      31243936                34.79 ns/op
BenchmarkTs2Int-16      29591794                34.35 ns/op
BenchmarkTs2Int-16      30912422                34.46 ns/op
BenchmarkTs2Int-16      34785256                34.28 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  13.389s
---
