= BenchmarkTs2Int

== i7-4600U
=== 32bit

[source]
---
PS C:\slackdump\internal\fasttime>go test . -bench ".*" -count=10
goos: windows
goarch: 386
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
BenchmarkTs2Int-4        3084236               388.5 ns/op
BenchmarkTs2Int-4        3130807               379.5 ns/op
BenchmarkTs2Int-4        3134098               382.9 ns/op
BenchmarkTs2Int-4        3142426               378.4 ns/op
BenchmarkTs2Int-4        3133819               382.8 ns/op
BenchmarkTs2Int-4        3152484               376.7 ns/op
BenchmarkTs2Int-4        3076028               377.8 ns/op
BenchmarkTs2Int-4        3143527               379.2 ns/op
BenchmarkTs2Int-4        3134566               380.1 ns/op
BenchmarkTs2Int-4        3152730               378.8 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  16.000s
---

=== 64bit

[source]
---   
PS C:\slackdump\internal\fasttime> go test . -bench ".*" -count=10
goos: windows
goarch: amd64
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
BenchmarkTs2Int-4       15718426                73.29 ns/op
BenchmarkTs2Int-4       16554610                72.74 ns/op
BenchmarkTs2Int-4       13828022                73.78 ns/op
BenchmarkTs2Int-4       14210768                72.53 ns/op
BenchmarkTs2Int-4       14328169                74.43 ns/op
BenchmarkTs2Int-4       16349811                72.58 ns/op
BenchmarkTs2Int-4       16485547                72.99 ns/op
BenchmarkTs2Int-4       16368154                72.58 ns/op
BenchmarkTs2Int-4       13619184                73.89 ns/op
BenchmarkTs2Int-4       16509716                72.28 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  18.064s
---

== i9-9880H @ 2.30GHz
== 64bit

[source]
---
[3:30:15] 0:slackdump/internal/fasttime (v3-tests)> go test . -bench '.*' -count=10
goos: darwin
goarch: amd64
pkg: github.com/rusq/slackdump/v3/internal/fasttime
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkTs2Int-16      29724420                34.15 ns/op
BenchmarkTs2Int-16      30925324                34.26 ns/op
BenchmarkTs2Int-16      29584566                33.91 ns/op
BenchmarkTs2Int-16      35253584                34.05 ns/op
BenchmarkTs2Int-16      29480674                35.25 ns/op
BenchmarkTs2Int-16      29552312                34.18 ns/op
BenchmarkTs2Int-16      31243936                34.79 ns/op
BenchmarkTs2Int-16      29591794                34.35 ns/op
BenchmarkTs2Int-16      30912422                34.46 ns/op
BenchmarkTs2Int-16      34785256                34.28 ns/op
PASS
ok      github.com/rusq/slackdump/v3/internal/fasttime  13.389s
---
