// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rusq/slackdump/v4/internal/chunk/backend/dbase/repository (interfaces: AliasRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository/mock_alias.go . AliasRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	repository "github.com/rusq/slackdump/v4/internal/chunk/backend/dbase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAliasRepository is a mock of AliasRepository interface.
type MockAliasRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAliasRepositoryMockRecorder
	isgomock struct{}
}

// MockAliasRepositoryMockRecorder is the mock recorder for MockAliasRepository.
type MockAliasRepositoryMockRecorder struct {
	mock *MockAliasRepository
}

// NewMockAliasRepository creates a new mock instance.
func NewMockAliasRepository(ctrl *gomock.Controller) *MockAliasRepository {
	mock := &MockAliasRepository{ctrl: ctrl}
	mock.recorder = &MockAliasRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAliasRepository) EXPECT() *MockAliasRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockAliasRepository) All(ctx context.Context, conn sqlx.QueryerContext) ([]repository.DBAlias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, conn)
	ret0, _ := ret[0].([]repository.DBAlias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockAliasRepositoryMockRecorder) All(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockAliasRepository)(nil).All), ctx, conn)
}

// Delete mocks base method.
func (m *MockAliasRepository) Delete(ctx context.Context, conn sqlx.ExtContext, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, conn, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAliasRepositoryMockRecorder) Delete(ctx, conn, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAliasRepository)(nil).Delete), ctx, conn, channelID)
}

// Get mocks base method.
func (m *MockAliasRepository) Get(ctx context.Context, conn sqlx.QueryerContext, channelID string) (repository.DBAlias, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, conn, channelID)
	ret0, _ := ret[0].(repository.DBAlias)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAliasRepositoryMockRecorder) Get(ctx, conn, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAliasRepository)(nil).Get), ctx, conn, channelID)
}

// Set mocks base method.
func (m *MockAliasRepository) Set(ctx context.Context, conn sqlx.ExtContext, channelID, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, conn, channelID, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockAliasRepositoryMockRecorder) Set(ctx, conn, channelID, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockAliasRepository)(nil).Set), ctx, conn, channelID, alias)
}
