// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository (interfaces: SearchMessageRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository/mock_search_msg.go . SearchMessageRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	iter "iter"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	chunk "github.com/rusq/slackdump/v3/internal/chunk"
	repository "github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchMessageRepository is a mock of SearchMessageRepository interface.
type MockSearchMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSearchMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockSearchMessageRepositoryMockRecorder is the mock recorder for MockSearchMessageRepository.
type MockSearchMessageRepositoryMockRecorder struct {
	mock *MockSearchMessageRepository
}

// NewMockSearchMessageRepository creates a new mock instance.
func NewMockSearchMessageRepository(ctrl *gomock.Controller) *MockSearchMessageRepository {
	mock := &MockSearchMessageRepository{ctrl: ctrl}
	mock.recorder = &MockSearchMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchMessageRepository) EXPECT() *MockSearchMessageRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockSearchMessageRepository) All(ctx context.Context, conn sqlx.QueryerContext) (iter.Seq2[repository.DBSearchMessage, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, conn)
	ret0, _ := ret[0].(iter.Seq2[repository.DBSearchMessage, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockSearchMessageRepositoryMockRecorder) All(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockSearchMessageRepository)(nil).All), ctx, conn)
}

// AllForChunk mocks base method.
func (m *MockSearchMessageRepository) AllForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (iter.Seq2[repository.DBSearchMessage, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(iter.Seq2[repository.DBSearchMessage, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllForChunk indicates an expected call of AllForChunk.
func (mr *MockSearchMessageRepositoryMockRecorder) AllForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllForChunk", reflect.TypeOf((*MockSearchMessageRepository)(nil).AllForChunk), ctx, conn, chunkID)
}

// AllOfType mocks base method.
func (m *MockSearchMessageRepository) AllOfType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (iter.Seq2[repository.DBSearchMessage, error], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AllOfType", varargs...)
	ret0, _ := ret[0].(iter.Seq2[repository.DBSearchMessage, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllOfType indicates an expected call of AllOfType.
func (mr *MockSearchMessageRepositoryMockRecorder) AllOfType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllOfType", reflect.TypeOf((*MockSearchMessageRepository)(nil).AllOfType), varargs...)
}

// Count mocks base method.
func (m *MockSearchMessageRepository) Count(ctx context.Context, conn sqlx.QueryerContext) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockSearchMessageRepositoryMockRecorder) Count(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockSearchMessageRepository)(nil).Count), ctx, conn)
}

// CountType mocks base method.
func (m *MockSearchMessageRepository) CountType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountType", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountType indicates an expected call of CountType.
func (mr *MockSearchMessageRepositoryMockRecorder) CountType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountType", reflect.TypeOf((*MockSearchMessageRepository)(nil).CountType), varargs...)
}

// Get mocks base method.
func (m *MockSearchMessageRepository) Get(ctx context.Context, conn sqlx.ExtContext, id any) (repository.DBSearchMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, conn, id)
	ret0, _ := ret[0].(repository.DBSearchMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSearchMessageRepositoryMockRecorder) Get(ctx, conn, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSearchMessageRepository)(nil).Get), ctx, conn, id)
}

// GetType mocks base method.
func (m *MockSearchMessageRepository) GetType(ctx context.Context, conn sqlx.ExtContext, id any, ct ...chunk.ChunkType) (repository.DBSearchMessage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn, id}
	for _, a := range ct {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetType", varargs...)
	ret0, _ := ret[0].(repository.DBSearchMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockSearchMessageRepositoryMockRecorder) GetType(ctx, conn, id any, ct ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn, id}, ct...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockSearchMessageRepository)(nil).GetType), varargs...)
}

// Insert mocks base method.
func (m *MockSearchMessageRepository) Insert(ctx context.Context, conn sqlx.ExtContext, t ...*repository.DBSearchMessage) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range t {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSearchMessageRepositoryMockRecorder) Insert(ctx, conn any, t ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, t...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSearchMessageRepository)(nil).Insert), varargs...)
}

// InsertAll mocks base method.
func (m *MockSearchMessageRepository) InsertAll(ctx context.Context, pconn repository.PrepareExtContext, tt iter.Seq2[*repository.DBSearchMessage, error]) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAll", ctx, pconn, tt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAll indicates an expected call of InsertAll.
func (mr *MockSearchMessageRepositoryMockRecorder) InsertAll(ctx, pconn, tt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAll", reflect.TypeOf((*MockSearchMessageRepository)(nil).InsertAll), ctx, pconn, tt)
}

// OneForChunk mocks base method.
func (m *MockSearchMessageRepository) OneForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (repository.DBSearchMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OneForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(repository.DBSearchMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OneForChunk indicates an expected call of OneForChunk.
func (mr *MockSearchMessageRepositoryMockRecorder) OneForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OneForChunk", reflect.TypeOf((*MockSearchMessageRepository)(nil).OneForChunk), ctx, conn, chunkID)
}
