// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository (interfaces: FileRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository/mock_file.go . FileRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	iter "iter"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	chunk "github.com/rusq/slackdump/v3/internal/chunk"
	repository "github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
	isgomock struct{}
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockFileRepository) All(ctx context.Context, conn sqlx.QueryerContext) (iter.Seq2[repository.DBFile, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, conn)
	ret0, _ := ret[0].(iter.Seq2[repository.DBFile, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockFileRepositoryMockRecorder) All(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockFileRepository)(nil).All), ctx, conn)
}

// AllForChunk mocks base method.
func (m *MockFileRepository) AllForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (iter.Seq2[repository.DBFile, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(iter.Seq2[repository.DBFile, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllForChunk indicates an expected call of AllForChunk.
func (mr *MockFileRepositoryMockRecorder) AllForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllForChunk", reflect.TypeOf((*MockFileRepository)(nil).AllForChunk), ctx, conn, chunkID)
}

// AllOfType mocks base method.
func (m *MockFileRepository) AllOfType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (iter.Seq2[repository.DBFile, error], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AllOfType", varargs...)
	ret0, _ := ret[0].(iter.Seq2[repository.DBFile, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllOfType indicates an expected call of AllOfType.
func (mr *MockFileRepositoryMockRecorder) AllOfType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllOfType", reflect.TypeOf((*MockFileRepository)(nil).AllOfType), varargs...)
}

// Count mocks base method.
func (m *MockFileRepository) Count(ctx context.Context, conn sqlx.QueryerContext) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockFileRepositoryMockRecorder) Count(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockFileRepository)(nil).Count), ctx, conn)
}

// CountType mocks base method.
func (m *MockFileRepository) CountType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountType", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountType indicates an expected call of CountType.
func (mr *MockFileRepositoryMockRecorder) CountType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountType", reflect.TypeOf((*MockFileRepository)(nil).CountType), varargs...)
}

// Get mocks base method.
func (m *MockFileRepository) Get(ctx context.Context, conn sqlx.ExtContext, id any) (repository.DBFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, conn, id)
	ret0, _ := ret[0].(repository.DBFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFileRepositoryMockRecorder) Get(ctx, conn, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFileRepository)(nil).Get), ctx, conn, id)
}

// GetType mocks base method.
func (m *MockFileRepository) GetType(ctx context.Context, conn sqlx.ExtContext, id any, ct ...chunk.ChunkType) (repository.DBFile, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn, id}
	for _, a := range ct {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetType", varargs...)
	ret0, _ := ret[0].(repository.DBFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockFileRepositoryMockRecorder) GetType(ctx, conn, id any, ct ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn, id}, ct...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockFileRepository)(nil).GetType), varargs...)
}

// Insert mocks base method.
func (m *MockFileRepository) Insert(ctx context.Context, conn sqlx.ExtContext, t ...*repository.DBFile) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range t {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockFileRepositoryMockRecorder) Insert(ctx, conn any, t ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, t...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockFileRepository)(nil).Insert), varargs...)
}

// InsertAll mocks base method.
func (m *MockFileRepository) InsertAll(ctx context.Context, pconn repository.PrepareExtContext, tt iter.Seq2[*repository.DBFile, error]) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAll", ctx, pconn, tt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAll indicates an expected call of InsertAll.
func (mr *MockFileRepositoryMockRecorder) InsertAll(ctx, pconn, tt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAll", reflect.TypeOf((*MockFileRepository)(nil).InsertAll), ctx, pconn, tt)
}

// OneForChunk mocks base method.
func (m *MockFileRepository) OneForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (repository.DBFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OneForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(repository.DBFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OneForChunk indicates an expected call of OneForChunk.
func (mr *MockFileRepositoryMockRecorder) OneForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OneForChunk", reflect.TypeOf((*MockFileRepository)(nil).OneForChunk), ctx, conn, chunkID)
}
