// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository (interfaces: ChannelUserRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository/mock_chan_user.go . ChannelUserRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	iter "iter"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	chunk "github.com/rusq/slackdump/v3/internal/chunk"
	repository "github.com/rusq/slackdump/v3/internal/chunk/backend/dbase/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelUserRepository is a mock of ChannelUserRepository interface.
type MockChannelUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChannelUserRepositoryMockRecorder
	isgomock struct{}
}

// MockChannelUserRepositoryMockRecorder is the mock recorder for MockChannelUserRepository.
type MockChannelUserRepositoryMockRecorder struct {
	mock *MockChannelUserRepository
}

// NewMockChannelUserRepository creates a new mock instance.
func NewMockChannelUserRepository(ctrl *gomock.Controller) *MockChannelUserRepository {
	mock := &MockChannelUserRepository{ctrl: ctrl}
	mock.recorder = &MockChannelUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelUserRepository) EXPECT() *MockChannelUserRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockChannelUserRepository) All(ctx context.Context, conn sqlx.QueryerContext) (iter.Seq2[repository.DBChannelUser, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, conn)
	ret0, _ := ret[0].(iter.Seq2[repository.DBChannelUser, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockChannelUserRepositoryMockRecorder) All(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockChannelUserRepository)(nil).All), ctx, conn)
}

// AllForChunk mocks base method.
func (m *MockChannelUserRepository) AllForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (iter.Seq2[repository.DBChannelUser, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(iter.Seq2[repository.DBChannelUser, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllForChunk indicates an expected call of AllForChunk.
func (mr *MockChannelUserRepositoryMockRecorder) AllForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllForChunk", reflect.TypeOf((*MockChannelUserRepository)(nil).AllForChunk), ctx, conn, chunkID)
}

// AllOfType mocks base method.
func (m *MockChannelUserRepository) AllOfType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (iter.Seq2[repository.DBChannelUser, error], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AllOfType", varargs...)
	ret0, _ := ret[0].(iter.Seq2[repository.DBChannelUser, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllOfType indicates an expected call of AllOfType.
func (mr *MockChannelUserRepositoryMockRecorder) AllOfType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllOfType", reflect.TypeOf((*MockChannelUserRepository)(nil).AllOfType), varargs...)
}

// Count mocks base method.
func (m *MockChannelUserRepository) Count(ctx context.Context, conn sqlx.QueryerContext) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, conn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockChannelUserRepositoryMockRecorder) Count(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockChannelUserRepository)(nil).Count), ctx, conn)
}

// CountType mocks base method.
func (m *MockChannelUserRepository) CountType(ctx context.Context, conn sqlx.QueryerContext, chunkTypeID ...chunk.ChunkType) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range chunkTypeID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountType", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountType indicates an expected call of CountType.
func (mr *MockChannelUserRepositoryMockRecorder) CountType(ctx, conn any, chunkTypeID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, chunkTypeID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountType", reflect.TypeOf((*MockChannelUserRepository)(nil).CountType), varargs...)
}

// Get mocks base method.
func (m *MockChannelUserRepository) Get(ctx context.Context, conn sqlx.ExtContext, id any) (repository.DBChannelUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, conn, id)
	ret0, _ := ret[0].(repository.DBChannelUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockChannelUserRepositoryMockRecorder) Get(ctx, conn, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChannelUserRepository)(nil).Get), ctx, conn, id)
}

// GetByChannelID mocks base method.
func (m *MockChannelUserRepository) GetByChannelID(ctx context.Context, db sqlx.QueryerContext, channelID string) (iter.Seq2[repository.DBChannelUser, error], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChannelID", ctx, db, channelID)
	ret0, _ := ret[0].(iter.Seq2[repository.DBChannelUser, error])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByChannelID indicates an expected call of GetByChannelID.
func (mr *MockChannelUserRepositoryMockRecorder) GetByChannelID(ctx, db, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChannelID", reflect.TypeOf((*MockChannelUserRepository)(nil).GetByChannelID), ctx, db, channelID)
}

// GetType mocks base method.
func (m *MockChannelUserRepository) GetType(ctx context.Context, conn sqlx.ExtContext, id any, ct ...chunk.ChunkType) (repository.DBChannelUser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn, id}
	for _, a := range ct {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetType", varargs...)
	ret0, _ := ret[0].(repository.DBChannelUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetType indicates an expected call of GetType.
func (mr *MockChannelUserRepositoryMockRecorder) GetType(ctx, conn, id any, ct ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn, id}, ct...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockChannelUserRepository)(nil).GetType), varargs...)
}

// Insert mocks base method.
func (m *MockChannelUserRepository) Insert(ctx context.Context, conn sqlx.ExtContext, t ...*repository.DBChannelUser) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, conn}
	for _, a := range t {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockChannelUserRepositoryMockRecorder) Insert(ctx, conn any, t ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, conn}, t...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockChannelUserRepository)(nil).Insert), varargs...)
}

// InsertAll mocks base method.
func (m *MockChannelUserRepository) InsertAll(ctx context.Context, pconn repository.PrepareExtContext, tt iter.Seq2[*repository.DBChannelUser, error]) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAll", ctx, pconn, tt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAll indicates an expected call of InsertAll.
func (mr *MockChannelUserRepositoryMockRecorder) InsertAll(ctx, pconn, tt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAll", reflect.TypeOf((*MockChannelUserRepository)(nil).InsertAll), ctx, pconn, tt)
}

// OneForChunk mocks base method.
func (m *MockChannelUserRepository) OneForChunk(ctx context.Context, conn sqlx.QueryerContext, chunkID int64) (repository.DBChannelUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OneForChunk", ctx, conn, chunkID)
	ret0, _ := ret[0].(repository.DBChannelUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OneForChunk indicates an expected call of OneForChunk.
func (mr *MockChannelUserRepositoryMockRecorder) OneForChunk(ctx, conn, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OneForChunk", reflect.TypeOf((*MockChannelUserRepository)(nil).OneForChunk), ctx, conn, chunkID)
}
