// Code generated by "stringer -type dumptype -trimprefix=dt convert.go"; DO NOT EDIT.

package convert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dtUnknown-0]
	_ = x[dtConversation-1]
	_ = x[dtChannels-2]
	_ = x[dtUsers-3]
}

const _dumptype_name = "UnknownConversationChannelsUsers"

var _dumptype_index = [...]uint8{0, 7, 19, 27, 32}

func (i dumptype) String() string {
	if i >= dumptype(len(_dumptype_index)-1) {
		return "dumptype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dumptype_name[_dumptype_index[i]:_dumptype_index[i+1]]
}
