// Code generated by "stringer -type=StorageType -trimprefix=ST"; DO NOT EDIT.

package fileproc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STNone-0]
	_ = x[STStandard-1]
	_ = x[STMattermost-2]
}

const _StorageType_name = "NoneStandardMattermost"

var _StorageType_index = [...]uint8{0, 4, 12, 22}

func (i StorageType) String() string {
	if i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
