// Code generated by "stringer -type=StorageType -trimprefix=ST"; DO NOT EDIT.

package source

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STnone-0]
	_ = x[STstandard-1]
	_ = x[STmattermost-2]
	_ = x[STdump-3]
	_ = x[STAvatar-4]
}

const _StorageType_name = "nonestandardmattermostdumpAvatar"

var _StorageType_index = [...]uint8{0, 4, 12, 22, 26, 32}

func (i StorageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StorageType_index)-1 {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[idx]:_StorageType_index[idx+1]]
}
