// Code generated by MockGen. DO NOT EDIT.
// Source: workspaceui.go
//
// Generated by this command:
//
//	mockgen -package workspaceui -destination=test_mock_manager.go -source workspaceui.go manager
//

// Package workspaceui is a generated GoMock package.
package workspaceui

import (
	context "context"
	reflect "reflect"

	auth "github.com/rusq/slackdump/v3/auth"
	gomock "go.uber.org/mock/gomock"
)

// Mockmanager is a mock of manager interface.
type Mockmanager struct {
	ctrl     *gomock.Controller
	recorder *MockmanagerMockRecorder
	isgomock struct{}
}

// MockmanagerMockRecorder is the mock recorder for Mockmanager.
type MockmanagerMockRecorder struct {
	mock *Mockmanager
}

// NewMockmanager creates a new mock instance.
func NewMockmanager(ctrl *gomock.Controller) *Mockmanager {
	mock := &Mockmanager{ctrl: ctrl}
	mock.recorder = &MockmanagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmanager) EXPECT() *MockmanagerMockRecorder {
	return m.recorder
}

// CreateAndSelect mocks base method.
func (m *Mockmanager) CreateAndSelect(ctx context.Context, p auth.Provider) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndSelect", ctx, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndSelect indicates an expected call of CreateAndSelect.
func (mr *MockmanagerMockRecorder) CreateAndSelect(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndSelect", reflect.TypeOf((*Mockmanager)(nil).CreateAndSelect), ctx, p)
}

// Delete mocks base method.
func (m *Mockmanager) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockmanagerMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockmanager)(nil).Delete), name)
}

// Select mocks base method.
func (m *Mockmanager) Select(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Select indicates an expected call of Select.
func (mr *MockmanagerMockRecorder) Select(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*Mockmanager)(nil).Select), name)
}
