// Package updater provides online update and version checking functions.
package updater

import (
	"context"
	"net/http"
	"net/http/httptest"
	"reflect"
	"testing"
	"time"
)

func TestUpdater_getLatestRelease(t *testing.T) {
	type fields struct {
		ghReleaseURL string
	}
	type args struct {
		ctx context.Context
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		srvBody []byte
		srvResp int
		want    *ghReleaseResponse
		wantErr bool
	}{
		{
			name: "checks OK",
			fields: fields{
				ghReleaseURL: "set by the test",
			},
			args: args{
				ctx: t.Context(),
			},
			srvBody: []byte(testReleasesResp),
			srvResp: http.StatusOK,
			want: &ghReleaseResponse{
				TagName:     "v3.1.6",
				PublishedAt: time.Date(2025, 6, 28, 10, 53, 39, 0, time.UTC),
				Body:        "## Changelog\n* 57c03383b672417d8a1a0b69ce2e699745638845 Merge pull request #532 from rusq/readme-upd-202506\n* 273b44782c4843ec24f7497d1a502cd2149b2b9c Merge pull request #534 from rusq/i533\n* 2f03d13e5dab15f065dc1b46ea98bfca383608a5 fix comments\n* cfb857dbcf90a1c03892dd1bfb06a2a949b35999 readme update\n* bb7689120ce986c7e018ba101cfeb7fe27161268 test for #533\n\n",
			},
			wantErr: false,
		},
		{
			name: "pre-release detected",
			fields: fields{
				ghReleaseURL: "set by the test",
			},
			args: args{
				ctx: t.Context(),
			},
			srvBody: []byte(`[{"tag_name":"v1.0.0","prerelease":true,"draft":true}]`),
			srvResp: http.StatusOK,
			want: &ghReleaseResponse{
				TagName:     "v1.0.0",
				PublishedAt: time.Time{},
				Body:        "",
				PreRelease:  true,
				Draft:       true,
			},
			wantErr: false,
		},
		{
			name: "invalid status code",
			fields: fields{
				ghReleaseURL: "set by the test",
			},
			args: args{
				ctx: t.Context(),
			},
			srvBody: []byte{},
			srvResp: http.StatusNotFound,
			want:    nil,
			wantErr: true,
		},
		{
			name: "empty response",
			fields: fields{
				ghReleaseURL: "set by the test",
			},
			args: args{
				ctx: t.Context(),
			},
			srvBody: []byte{},
			srvResp: http.StatusOK,
			want:    nil,
			wantErr: true,
		},
		{
			name: "not a valid version tag",
			fields: fields{
				ghReleaseURL: "set by the test",
			},
			args: args{
				ctx: t.Context(),
			},
			srvBody: []byte(`[{"name":"lol"}]`),
			srvResp: http.StatusOK,
			want:    nil,
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Write(tt.srvBody)
			}))
			t.Cleanup(func() { srv.Close() })
			u := &Updater{
				ghReleaseURL: srv.URL,
			}
			got, err := u.getLatestRelease(tt.args.ctx)
			if (err != nil) != tt.wantErr {
				t.Errorf("Updater.getLatestRelease() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Updater.getLatestRelease() = %v, want %v", got, tt.want)
			}
		})
	}
}

const testReleasesResp = `
[
  {
    "url": "https://api.github.com/repos/rusq/slackdump/releases/228527608",
    "assets_url": "https://api.github.com/repos/rusq/slackdump/releases/228527608/assets",
    "upload_url": "https://uploads.github.com/repos/rusq/slackdump/releases/228527608/assets{?name,label}",
    "html_url": "https://github.com/rusq/slackdump/releases/tag/v3.1.6",
    "id": 228527608,
    "author": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "node_id": "RE_kwDOGTeexM4Nnw34",
    "tag_name": "v3.1.6",
    "target_commitish": "master",
    "name": "v3.1.6",
    "draft": false,
    "immutable": false,
    "prerelease": false,
    "created_at": "2025-06-28T10:46:25Z",
    "published_at": "2025-06-28T10:53:39Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122265",
        "id": 268122265,
        "node_id": "RA_kwDOGTeexM4P-ziZ",
        "name": "checksums.txt",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "text/plain; charset=utf-8",
        "state": "uploaded",
        "size": 2340,
        "digest": "sha256:8dc23e49b5238b7c45ce312537601438f5e54123ec289907e37089e95002d710",
        "download_count": 9,
        "created_at": "2025-06-28T10:53:38Z",
        "updated_at": "2025-06-28T10:53:38Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/checksums.txt"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122249",
        "id": 268122249,
        "node_id": "RA_kwDOGTeexM4P-ziJ",
        "name": "slackdump_3.1.6_linux_386.apk",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.android.package-archive",
        "state": "uploaded",
        "size": 13288148,
        "digest": "sha256:1b2f0449ebdacd77362218279350208948b80d19e9b7024372397588fbfef862",
        "download_count": 19,
        "created_at": "2025-06-28T10:53:35Z",
        "updated_at": "2025-06-28T10:53:36Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_386.apk"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122260",
        "id": 268122260,
        "node_id": "RA_kwDOGTeexM4P-ziU",
        "name": "slackdump_3.1.6_linux_386.deb",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.debian.binary-package",
        "state": "uploaded",
        "size": 12321740,
        "digest": "sha256:4b5fd4945cb44daa5d8ad12fda979ea6c9a8e83b12b3b47256d81a8c1bc6e64b",
        "download_count": 48,
        "created_at": "2025-06-28T10:53:37Z",
        "updated_at": "2025-06-28T10:53:38Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_386.deb"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122262",
        "id": 268122262,
        "node_id": "RA_kwDOGTeexM4P-ziW",
        "name": "slackdump_3.1.6_linux_386.pkg.tar.zst",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zstd",
        "state": "uploaded",
        "size": 12721302,
        "digest": "sha256:fa9a7a9e43b67fd6811752b91a7a5f2277510ceca212e9478ef0d3c0dea732ad",
        "download_count": 9,
        "created_at": "2025-06-28T10:53:37Z",
        "updated_at": "2025-06-28T10:53:38Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_386.pkg.tar.zst"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122253",
        "id": 268122253,
        "node_id": "RA_kwDOGTeexM4P-ziN",
        "name": "slackdump_3.1.6_linux_386.rpm",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-rpm",
        "state": "uploaded",
        "size": 13286748,
        "digest": "sha256:1538a67a4f754178273ce73f359ba9f601a4e4f81726468221b243d5930907d0",
        "download_count": 10,
        "created_at": "2025-06-28T10:53:36Z",
        "updated_at": "2025-06-28T10:53:36Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_386.rpm"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122251",
        "id": 268122251,
        "node_id": "RA_kwDOGTeexM4P-ziL",
        "name": "slackdump_3.1.6_linux_amd64.apk",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.android.package-archive",
        "state": "uploaded",
        "size": 13921414,
        "digest": "sha256:8060a0075411fe87e56f349192b386e0ed5a2b6e581ae6c8e65807fd3b33b224",
        "download_count": 14,
        "created_at": "2025-06-28T10:53:35Z",
        "updated_at": "2025-06-28T10:53:36Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_amd64.apk"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122264",
        "id": 268122264,
        "node_id": "RA_kwDOGTeexM4P-ziY",
        "name": "slackdump_3.1.6_linux_amd64.deb",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.debian.binary-package",
        "state": "uploaded",
        "size": 12992536,
        "digest": "sha256:610fc9e77db820be161db4ce5256792be87c46bcc8638f60c9a19f170c9371f0",
        "download_count": 99,
        "created_at": "2025-06-28T10:53:38Z",
        "updated_at": "2025-06-28T10:53:39Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_amd64.deb"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122257",
        "id": 268122257,
        "node_id": "RA_kwDOGTeexM4P-ziR",
        "name": "slackdump_3.1.6_linux_amd64.pkg.tar.zst",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zstd",
        "state": "uploaded",
        "size": 13497066,
        "digest": "sha256:3265f126089a50a283c48c2db832564a139a7a223e385ba8411c3ec9397b7875",
        "download_count": 71,
        "created_at": "2025-06-28T10:53:36Z",
        "updated_at": "2025-06-28T10:53:37Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_amd64.pkg.tar.zst"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122250",
        "id": 268122250,
        "node_id": "RA_kwDOGTeexM4P-ziK",
        "name": "slackdump_3.1.6_linux_amd64.rpm",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-rpm",
        "state": "uploaded",
        "size": 13878890,
        "digest": "sha256:3fbb97d93807491e47d93af598d30a03979133ecb839a3c0235302070a33895b",
        "download_count": 21,
        "created_at": "2025-06-28T10:53:35Z",
        "updated_at": "2025-06-28T10:53:36Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_amd64.rpm"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122248",
        "id": 268122248,
        "node_id": "RA_kwDOGTeexM4P-ziI",
        "name": "slackdump_3.1.6_linux_arm64.apk",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.android.package-archive",
        "state": "uploaded",
        "size": 13115320,
        "digest": "sha256:660e228c90f48c9bcd20914042983cd26e0231cc917c318512a9806eb0326256",
        "download_count": 11,
        "created_at": "2025-06-28T10:53:35Z",
        "updated_at": "2025-06-28T10:53:35Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_arm64.apk"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122258",
        "id": 268122258,
        "node_id": "RA_kwDOGTeexM4P-ziS",
        "name": "slackdump_3.1.6_linux_arm64.deb",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/vnd.debian.binary-package",
        "state": "uploaded",
        "size": 12210430,
        "digest": "sha256:8065bfe0eea8a687c03fb36a2756f3b772f341e431408bc2292656ee43ca8d6d",
        "download_count": 29,
        "created_at": "2025-06-28T10:53:36Z",
        "updated_at": "2025-06-28T10:53:37Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_arm64.deb"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122263",
        "id": 268122263,
        "node_id": "RA_kwDOGTeexM4P-ziX",
        "name": "slackdump_3.1.6_linux_arm64.pkg.tar.zst",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zstd",
        "state": "uploaded",
        "size": 12596709,
        "digest": "sha256:7bef94ef94d8d6fab77d1ce83ae8670a33fbbb2a8bb343cf799c021d840c9ff4",
        "download_count": 4,
        "created_at": "2025-06-28T10:53:38Z",
        "updated_at": "2025-06-28T10:53:38Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_arm64.pkg.tar.zst"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122256",
        "id": 268122256,
        "node_id": "RA_kwDOGTeexM4P-ziQ",
        "name": "slackdump_3.1.6_linux_arm64.rpm",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-rpm",
        "state": "uploaded",
        "size": 13133911,
        "digest": "sha256:75ec7c32b859e2554709ae3d4a6ee427d5809fb03ce4df1e6cf7dd3b73663acb",
        "download_count": 7,
        "created_at": "2025-06-28T10:53:36Z",
        "updated_at": "2025-06-28T10:53:37Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_3.1.6_linux_arm64.rpm"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122230",
        "id": 268122230,
        "node_id": "RA_kwDOGTeexM4P-zh2",
        "name": "slackdump_Freebsd_arm64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 10324774,
        "digest": "sha256:3e728121147f06cc1d2646642d0dabd5696cb02acdf30ed3bbf84cd24203029c",
        "download_count": 4,
        "created_at": "2025-06-28T10:53:30Z",
        "updated_at": "2025-06-28T10:53:31Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Freebsd_arm64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122236",
        "id": 268122236,
        "node_id": "RA_kwDOGTeexM4P-zh8",
        "name": "slackdump_Freebsd_x86_64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 11104484,
        "digest": "sha256:6f2bebd852a940a05f8463b5ae35d43aede3cf3fa508d8edfb039686ac9d299e",
        "download_count": 5,
        "created_at": "2025-06-28T10:53:32Z",
        "updated_at": "2025-06-28T10:53:33Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Freebsd_x86_64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122231",
        "id": 268122231,
        "node_id": "RA_kwDOGTeexM4P-zh3",
        "name": "slackdump_Linux_arm64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 12188972,
        "digest": "sha256:737fd3741ab0175763cf77b3defb10c057cda90d28ec9eb9f64140356bd1817a",
        "download_count": 12,
        "created_at": "2025-06-28T10:53:30Z",
        "updated_at": "2025-06-28T10:53:31Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Linux_arm64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122232",
        "id": 268122232,
        "node_id": "RA_kwDOGTeexM4P-zh4",
        "name": "slackdump_Linux_i386.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 12302337,
        "digest": "sha256:189813e72d0669db3f914c237bde61e9357e385cee722254f76736e576dcfb50",
        "download_count": 4,
        "created_at": "2025-06-28T10:53:30Z",
        "updated_at": "2025-06-28T10:53:31Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Linux_i386.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122237",
        "id": 268122237,
        "node_id": "RA_kwDOGTeexM4P-zh9",
        "name": "slackdump_Linux_x86_64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 12964088,
        "digest": "sha256:0bf28075efaa7fce2f4c3744fcf25d70a3a82f0ca57d84e8514a7004cba20833",
        "download_count": 202,
        "created_at": "2025-06-28T10:53:32Z",
        "updated_at": "2025-06-28T10:53:33Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Linux_x86_64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122242",
        "id": 268122242,
        "node_id": "RA_kwDOGTeexM4P-ziC",
        "name": "slackdump_macOS_arm64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 12823830,
        "digest": "sha256:8322bc287f336bc060a6318e9913f6ac6733bfeb57b27605333b40fbace3ec69",
        "download_count": 95,
        "created_at": "2025-06-28T10:53:33Z",
        "updated_at": "2025-06-28T10:53:34Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_macOS_arm64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122243",
        "id": 268122243,
        "node_id": "RA_kwDOGTeexM4P-ziD",
        "name": "slackdump_macOS_x86_64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 13351959,
        "digest": "sha256:d8ac57e68656dbc1dc2b55e61249265a87306838191359e938f14f4a3c882190",
        "download_count": 31,
        "created_at": "2025-06-28T10:53:33Z",
        "updated_at": "2025-06-28T10:53:34Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_macOS_x86_64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122245",
        "id": 268122245,
        "node_id": "RA_kwDOGTeexM4P-ziF",
        "name": "slackdump_Openbsd_arm64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 10215033,
        "digest": "sha256:a88c6cf285adf0eb1520d588735749ca43e65eaeb02745487a7e513ceafbf01f",
        "download_count": 6,
        "created_at": "2025-06-28T10:53:33Z",
        "updated_at": "2025-06-28T10:53:34Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Openbsd_arm64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122244",
        "id": 268122244,
        "node_id": "RA_kwDOGTeexM4P-ziE",
        "name": "slackdump_Openbsd_x86_64.tar.gz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/gzip",
        "state": "uploaded",
        "size": 11034927,
        "digest": "sha256:a9467f14dd65186728831643dd0c6e77957c5ad7c8205c8e1a46618822dca289",
        "download_count": 5,
        "created_at": "2025-06-28T10:53:33Z",
        "updated_at": "2025-06-28T10:53:34Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Openbsd_x86_64.tar.gz"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122228",
        "id": 268122228,
        "node_id": "RA_kwDOGTeexM4P-zh0",
        "name": "slackdump_Windows_arm64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 11377775,
        "digest": "sha256:0e0b04ee74544b34e86e91d2e841d643871967d6baec4bd529d9f44e4bfba98a",
        "download_count": 42,
        "created_at": "2025-06-28T10:53:30Z",
        "updated_at": "2025-06-28T10:53:31Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Windows_arm64.zip"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122235",
        "id": 268122235,
        "node_id": "RA_kwDOGTeexM4P-zh7",
        "name": "slackdump_Windows_i386.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 11823250,
        "digest": "sha256:cf9f9c11b7e98074e56bc3d31b9af9282eef6eb9a719440dcb4204eee7efa762",
        "download_count": 62,
        "created_at": "2025-06-28T10:53:32Z",
        "updated_at": "2025-06-28T10:53:33Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Windows_i386.zip"
      },
      {
        "url": "https://api.github.com/repos/rusq/slackdump/releases/assets/268122240",
        "id": 268122240,
        "node_id": "RA_kwDOGTeexM4P-ziA",
        "name": "slackdump_Windows_x86_64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 12364341,
        "digest": "sha256:4d66075be772d37838fb017cde9449082fde14350a10da6af3207931d54e6d35",
        "download_count": 429,
        "created_at": "2025-06-28T10:53:32Z",
        "updated_at": "2025-06-28T10:53:33Z",
        "browser_download_url": "https://github.com/rusq/slackdump/releases/download/v3.1.6/slackdump_Windows_x86_64.zip"
      }
    ],
    "tarball_url": "https://api.github.com/repos/rusq/slackdump/tarball/v3.1.6",
    "zipball_url": "https://api.github.com/repos/rusq/slackdump/zipball/v3.1.6",
    "body": "## Changelog\n* 57c03383b672417d8a1a0b69ce2e699745638845 Merge pull request #532 from rusq/readme-upd-202506\n* 273b44782c4843ec24f7497d1a502cd2149b2b9c Merge pull request #534 from rusq/i533\n* 2f03d13e5dab15f065dc1b46ea98bfca383608a5 fix comments\n* cfb857dbcf90a1c03892dd1bfb06a2a949b35999 readme update\n* bb7689120ce986c7e018ba101cfeb7fe27161268 test for #533\n\n"
  }
]`
