name: dickerhub

on:
    release:
        types:
            - published
    push:
        branches: [master,v3.0.x]


# reference:
# 1. https://docs.docker.com/build/ci/github-actions/push-multi-registries/
# 2. https://github.com/docker/metadata-action?tab=readme-ov-file#typeraw
# 3. 

jobs:
    push_to_dockerhub:
        name: Push image to dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images:
                  ffffuuu/slackdump
                tags: |
                  type=raw,value=latest  
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
