// Code generated by "stringer -trimprefix ent -type entityType"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[entMessages-0]
	_ = x[entCanvasMessages-1]
	_ = x[entUsers-2]
	_ = x[entChannels-3]
	_ = x[entChannelUsers-4]
	_ = x[entFiles-5]
}

const _entityType_name = "MessagesCanvasMessagesUsersChannelsChannelUsersFiles"

var _entityType_index = [...]uint8{0, 8, 22, 27, 35, 47, 52}

func (i entityType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_entityType_index)-1 {
		return "entityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _entityType_name[_entityType_index[idx]:_entityType_index[idx+1]]
}
